apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-gqok
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-85-tenant/test-rhtap-85-app/devfile-sample-code-with-quarkus-gqok@sha256:90c5d64695655a9b5126c02f243b39a70cfa5307081f0ba5ca77f7180a29eb2c
        name: my-java-quarkus
        resources: {}
status: {}
